version: '3.8'

services:
  # PostgreSQLデータベース
  db:
    image: postgres:16-alpine
    container_name: simple-kanban-db
    environment:
      POSTGRES_DB: simple_kanban
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Simple Kanban API
  api:
    build: .
    container_name: simple-kanban-api
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      GIN_MODE: debug
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: simple_kanban
      DB_SSL_MODE: disable
      JWT_SECRET: your-secret-key-change-this-in-production
      JWT_EXPIRE_HOURS: 24
      JWT_REFRESH_HOURS: 168
      JWT_COOKIE_NAME: auth_token
      JWT_COOKIE_SECURE: false
      JWT_COOKIE_HTTP_ONLY: true
      JWT_COOKIE_SAME_SITE: Lax
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  default:
    name: simple-kanban-network 